export const data = [
    {
        "brandName": "Bioviz P Cap",
        "category": "Probiotic",
        "subcategory": "  ",
        "ingredient1": "Lactobacillus",
        "ingredient2": "Bifidobacterium",
        "unit": "Capsule",
        "ptr": "94.92",
        "pharma": "Medivista",
        "undefined": " "
    },
    {
        "brandName": "Cetfran Syp",
        "category": "Cough syrup",
        "subcategory": "  ",
        "ingredient1": "Dextromethorphan",
        "ingredient2": "Phenlyephrine",
        "unit": "Syrup",
        "ptr": "58.57",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Cefmixet 200",
        "category": "Antibiotic",
        "subcategory": "Cephalosporin",
        "ingredient1": "Cefpodoxime",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "142.86",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Cefmixet Dry syrup",
        "category": "Antibiotic",
        "subcategory": "Cephalosporin",
        "ingredient1": "Cefpodoxime",
        "ingredient2": " ",
        "unit": "Syrup",
        "ptr": "60.71",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Diclomide gel",
        "category": "Analgesic",
        "subcategory": "       ",
        "ingredient1": "Diclofenac",
        "ingredient2": "methyl, linseed oil, menthol",
        "unit": "Gel",
        "ptr": "53.57",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Irethro 250",
        "category": "Antibiotic",
        "subcategory": "       ",
        "ingredient1": "Azithromycin",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "83.18",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Irecef 500",
        "category": "Antibiotic",
        "subcategory": "Cephalosporin",
        "ingredient1": "Cefuroxime",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "407.14",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Iremox CA",
        "category": "Antibiotic",
        "subcategory": "       ",
        "ingredient1": "Amoxycillin Clavulanic acid",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "85.71",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Irethro 500",
        "category": "Antibiotic",
        "subcategory": "       ",
        "ingredient1": "Azithromycin",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "50.71",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Irime- LBTAB",
        "category": "Antibiotic",
        "subcategory": "Cephalosporin",
        "ingredient1": "Cefixime",
        "ingredient2": "Lactic acid",
        "unit": "Tablet",
        "ptr": "107.14",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Lycolin",
        "category": "Supplement",
        "subcategory": "       ",
        "ingredient1": "Lycopene, copper, selenium, iodine, zinc",
        "ingredient2": "Cyanacobalamin, folic acid, nicotinamide",
        "unit": "Syrup",
        "ptr": "107.14",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Ricob 90",
        "category": "Analgesic",
        "subcategory": "       ",
        "ingredient1": "Etorocoxib",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "70",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Kuflax",
        "category": "Cough syrup",
        "subcategory": "       ",
        "ingredient1": "Terbutaline",
        "ingredient2": "Ambroxol, guaiphenesin, menthol",
        "unit": "Syrup",
        "ptr": "60.71",
        "pharma": "Medivista",
        "undefined": " "
    },
    {
        "brandName": "Shurecal",
        "category": "Supplement",
        "subcategory": "Mineral",
        "ingredient1": "Calcium",
        "ingredient2": " ",
        "unit": "Suspension",
        "ptr": "70",
        "pharma": "AIS",
        "undefined": " "
    },
    {
        "brandName": "Brutraxin D",
        "category": "Analgesic",
        "subcategory": "       ",
        "ingredient1": "Trypsin, bromolexin, rutoside, diclofenac",
        "ingredient2": "Diclofenac",
        "unit": "Tablet",
        "ptr": "142.14",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Mefeliton",
        "category": "Analgesic",
        "subcategory": "       ",
        "ingredient1": "Mefenamic acid",
        "ingredient2": "Dicyclomine",
        "unit": "Tablet",
        "ptr": "28.57",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Cetjoint K27",
        "category": "Supplement",
        "subcategory": "Mineral",
        "ingredient1": "Calcitriol",
        "ingredient2": "Calcium carbonate, vitamin K2-7",
        "unit": "Capsule",
        "ptr": "121.43",
        "pharma": "Leeford",
        "undefined": " "
    },
    {
        "brandName": "Glipiride 1",
        "category": "Anti-Diabetic",
        "subcategory": "       ",
        "ingredient1": "Glimepiride",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "28.79",
        "pharma": "Leeford",
        "undefined": " "
    },
    {
        "brandName": "Flexen - OS",
        "category": "Antacid",
        "subcategory": "aluminium hydroxide and a sulphate derivative of sucrose.",
        "ingredient1": "sucralfate",
        "ingredient2": "Oxetacaine",
        "unit": "Syrup",
        "ptr": "85.71",
        "pharma": "Medivista",
        "undefined": " "
    },
    {
        "brandName": "Moxyviz 375",
        "category": "Antibiotic",
        "subcategory": "       ",
        "ingredient1": "Amoxycillin Clavulanic acid",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "85.71",
        "pharma": "Medivista",
        "undefined": " "
    },
    {
        "brandName": "Pregaviz-M",
        "category": "Analgesic",
        "subcategory": "anticonvulsant, analgesic and anxiolytic",
        "ingredient1": "Pregabalin",
        "ingredient2": "Methylcobalamin",
        "unit": "Tablet",
        "ptr": "89.28",
        "pharma": "Medivista",
        "undefined": " "
    },
    {
        "brandName": "Lufee cream 30 gm",
        "category": "Antifungal",
        "subcategory": "       ",
        "ingredient1": "Luliconazole",
        "ingredient2": " ",
        "unit": "Cream",
        "ptr": "196.43",
        "pharma": "TAR",
        "undefined": " "
    },
    {
        "brandName": "Pantozee inj",
        "category": "Antacid",
        "subcategory": "PPI",
        "ingredient1": "Pantoprazole",
        "ingredient2": " ",
        "unit": "Injection",
        "ptr": "35.71",
        "pharma": "ZEE",
        "undefined": " "
    },
    {
        "brandName": "Smithcee plus",
        "category": "Supplement",
        "subcategory": "Vitamin",
        "ingredient1": "Vitamin C",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "42.86",
        "pharma": "GLE",
        "undefined": " "
    },
    {
        "brandName": "Bioviz sachet",
        "category": "Probiotic",
        "subcategory": "       ",
        "ingredient1": " ",
        "ingredient2": " ",
        "unit": "Powder",
        "ptr": "18.98",
        "pharma": "Medivista",
        "undefined": " "
    },
    {
        "brandName": "Caltrorin Cal-D3",
        "category": "Supplement",
        "subcategory": "       ",
        "ingredient1": "Calcium carbonate",
        "ingredient2": "calcitriol, omega 3, methylcobalamin, boron, folic acid",
        "unit": "Capsule",
        "ptr": "157.14",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Irenac MR",
        "category": "Analgesic",
        "subcategory": "Muscle Relaxant",
        "ingredient1": "Aceclofenac",
        "ingredient2": "Paracetamol, chlorzoxazone",
        "unit": "Tablet",
        "ptr": "57.14",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Irento-40",
        "category": "Antacid",
        "subcategory": "PPI",
        "ingredient1": "Pantoprazole",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "42.86",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Proteadd-Plus",
        "category": "Supplement",
        "subcategory": "Protein powder",
        "ingredient1": " ",
        "ingredient2": " ",
        "unit": "Powder",
        "ptr": "186.44",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Livertine XL",
        "category": "Supplement",
        "subcategory": "Ayurvedic",
        "ingredient1": " ",
        "ingredient2": " ",
        "unit": "Syrup",
        "ptr": "85.72",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Pirolacin DT",
        "category": "Analgesic",
        "subcategory": "       ",
        "ingredient1": "Piroxicam",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "27.07",
        "pharma": "Irene",
        "undefined": " "
    },
    {
        "brandName": "Kalciviz-CT",
        "category": "Supplement",
        "subcategory": "       ",
        "ingredient1": "Calcitriol",
        "ingredient2": "Calcium Citrate maleate, zinc, magnesium oxide",
        "unit": "Capsule",
        "ptr": "85.71",
        "pharma": "Medivista",
        "undefined": " "
    },
    {
        "brandName": "Citrol D3",
        "category": "Supplement",
        "subcategory": "       ",
        "ingredient1": "Vitamin D3",
        "ingredient2": " ",
        "unit": "Capsule",
        "ptr": "85.71",
        "pharma": "Medivista",
        "undefined": " "
    },
    {
        "brandName": "Citrol D3",
        "category": "Supplement",
        "subcategory": "       ",
        "ingredient1": "Vitamin D3",
        "ingredient2": " ",
        "unit": "Powder",
        "ptr": "20.33",
        "pharma": "Medivista",
        "undefined": " "
    },
    {
        "brandName": "Meditron med",
        "category": "Antiemetic",
        "subcategory": "       ",
        "ingredient1": "Ondansetron",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "37.14",
        "pharma": "Medivista",
        "undefined": " "
    },
    {
        "brandName": "Hyrox-25",
        "category": "Antihistamine",
        "subcategory": "       ",
        "ingredient1": "Hydroxyzine",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "25",
        "pharma": "Medivista",
        "undefined": " "
    },
    {
        "brandName": "Acenex Plus",
        "category": "Analgesic",
        "subcategory": "       ",
        "ingredient1": " ",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "12",
        "pharma": "Bione",
        "undefined": " "
    },
    {
        "brandName": "MDIC gel 30 gm",
        "category": "Analgesic",
        "subcategory": "       ",
        "ingredient1": "Diclofenac",
        "ingredient2": "Menthol",
        "unit": "Gel",
        "ptr": "18",
        "pharma": "MRG",
        "undefined": " "
    },
    {
        "brandName": "Omcure 20 mg",
        "category": "Antacid",
        "subcategory": "       ",
        "ingredient1": "Omeprazole",
        "ingredient2": " ",
        "unit": "Capsule",
        "ptr": "10",
        "pharma": "FINE",
        "undefined": " "
    },
    {
        "brandName": "Pantonext 40mg",
        "category": "Antacid",
        "subcategory": "PPI",
        "ingredient1": "Pantoprazole",
        "ingredient2": " ",
        "unit": "Injection",
        "ptr": "12",
        "pharma": "Bione",
        "undefined": " "
    },
    {
        "brandName": "Cacitate Plus",
        "category": "Supplement",
        "subcategory": "       ",
        "ingredient1": "Calcium 100",
        "ingredient2": "Vit D3 200",
        "unit": "Syrup",
        "ptr": "14",
        "pharma": "FINE",
        "undefined": " "
    },
    {
        "brandName": "Zincolive",
        "category": "Supplement",
        "subcategory": "       ",
        "ingredient1": " ",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "26",
        "pharma": "Iheal",
        "undefined": " "
    },
    {
        "brandName": "Nextbest Forte",
        "category": "Supplement",
        "subcategory": "zinc",
        "ingredient1": "Calcium pantothenate",
        "ingredient2": "calcium, copper, magnesium, manganese, zinc 50 mg, folic acid, iodine, niacinamide, phosphorus, Vitamin A, et",
        "unit": "Capsule",
        "ptr": "15",
        "pharma": "Bione",
        "undefined": " "
    },
    {
        "brandName": "Alext",
        "category": "Antihistamine",
        "subcategory": "       ",
        "ingredient1": "Levocetirizine",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "6",
        "pharma": "Bione",
        "undefined": " "
    },
    {
        "brandName": "Ferotex-FA Plus",
        "category": "Supplement",
        "subcategory": "       ",
        "ingredient1": " ",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "17",
        "pharma": "Bione",
        "undefined": " "
    },
    {
        "brandName": "Coldmart-P",
        "category": "Antihistamine",
        "subcategory": "Analgesic antipyretic",
        "ingredient1": "Paracetamol",
        "ingredient2": "Phenylephrine, diphenhydramine",
        "unit": "Tablet",
        "ptr": "12.5",
        "pharma": "IHeal",
        "undefined": " "
    },
    {
        "brandName": "Lulinext",
        "category": "Antifungal",
        "subcategory": "       ",
        "ingredient1": "Luliconazole",
        "ingredient2": " ",
        "unit": "Ointment",
        "ptr": "45",
        "pharma": "Bione",
        "undefined": " "
    },
    {
        "brandName": "Lorid tab",
        "category": "Antihistamine",
        "subcategory": "       ",
        "ingredient1": "Loratidine",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "39.52",
        "pharma": "FINE",
        "undefined": " "
    },
    {
        "brandName": "Ferotex",
        "category": "Supplement",
        "subcategory": "Iron",
        "ingredient1": "Ferrous",
        "ingredient2": " ",
        "unit": "Syrup",
        "ptr": "72.47",
        "pharma": "Bione",
        "undefined": " "
    },
    {
        "brandName": "Glipvil M 1000",
        "category": "Anti-Diabetic",
        "subcategory": "       ",
        "ingredient1": "Metformin",
        "ingredient2": "Vildagliptin",
        "unit": "Tablet",
        "ptr": "68.07",
        "pharma": "FINE",
        "undefined": " "
    },
    {
        "brandName": "Glipvil M 500",
        "category": "Anti-Diabetic",
        "subcategory": "       ",
        "ingredient1": "Metformin",
        "ingredient2": "Vildagliptin",
        "unit": "Tablet",
        "ptr": "54.9",
        "pharma": "FINE",
        "undefined": " "
    },
    {
        "brandName": "Mefmid D",
        "category": "Analgesic",
        "subcategory": "Antispasmodic",
        "ingredient1": "Mefenamic acid",
        "ingredient2": "Drotaverine",
        "unit": "Tablet",
        "ptr": "60",
        "pharma": "Tenwel",
        "undefined": " "
    },
    {
        "brandName": "Sedoxe-200",
        "category": "Antibiotic",
        "subcategory": "Cephalosporin",
        "ingredient1": "Cefpodoxime",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "192",
        "pharma": "Tenwel",
        "undefined": " "
    },
    {
        "brandName": "Neuroten N",
        "category": "Analgesic",
        "subcategory": "       ",
        "ingredient1": " ",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "68",
        "pharma": "Tenwel",
        "undefined": " "
    },
    {
        "brandName": "Sedoxe-50",
        "category": "Antibiotic",
        "subcategory": "Cephalosporin",
        "ingredient1": "Cefpodoxime",
        "ingredient2": " ",
        "unit": "Syrup",
        "ptr": "76",
        "pharma": "Tenwel",
        "undefined": " "
    },
    {
        "brandName": "Silyplex-L",
        "category": "Supplement",
        "subcategory": "       ",
        "ingredient1": "Silymarin",
        "ingredient2": "Thiamine, Vit B12",
        "unit": "Syrup",
        "ptr": "116",
        "pharma": "Tenwel",
        "undefined": " "
    },
    {
        "brandName": "L-hist mont Fx",
        "category": "Antihistamine",
        "subcategory": "       ",
        "ingredient1": " ",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "48.93",
        "pharma": "Alkem",
        "undefined": " "
    },
    {
        "brandName": "NS 100 ml",
        "category": "Fluid",
        "subcategory": "       ",
        "ingredient1": "Normal saline 0.9%",
        "ingredient2": " ",
        "unit": "Bottle",
        "ptr": "11.5",
        "pharma": "Alkem",
        "undefined": " "
    },
    {
        "brandName": "Cipcal 500",
        "category": "Supplement",
        "subcategory": "       ",
        "ingredient1": "Calcium",
        "ingredient2": "Vit D3",
        "unit": "Tablet",
        "ptr": "17.22",
        "pharma": "CIPLA",
        "undefined": " "
    },
    {
        "brandName": "Pantin IV",
        "category": "Antacid",
        "subcategory": "PPI",
        "ingredient1": "Pantoprazole",
        "ingredient2": " ",
        "unit": "Injection",
        "ptr": "13.4",
        "pharma": "HETRO",
        "undefined": " "
    },
    {
        "brandName": "DOO CLAV 30 ml",
        "category": "Antibiotic",
        "subcategory": "       ",
        "ingredient1": " ",
        "ingredient2": " ",
        "unit": "Syrup",
        "ptr": "27.04",
        "pharma": "LAB",
        "undefined": " "
    },
    {
        "brandName": "Freelex",
        "category": "Laxative",
        "subcategory": "       ",
        "ingredient1": "Bisacodyl",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "4.39",
        "pharma": "Leeford",
        "undefined": " "
    },
    {
        "brandName": "Chyreal forte",
        "category": "Supplement",
        "subcategory": "       ",
        "ingredient1": "Trypsin",
        "ingredient2": "Chymotrypsin",
        "unit": "Tablet",
        "ptr": "50.04",
        "pharma": "Maxx",
        "undefined": " "
    },
    {
        "brandName": "Urin Bag Polymed",
        "category": "Equipment",
        "subcategory": "       ",
        "ingredient1": " ",
        "ingredient2": " ",
        "unit": "Equipment",
        "ptr": "26.4",
        "pharma": "Poly",
        "undefined": " "
    },
    {
        "brandName": "Aliclair 500",
        "category": "Antibiotic",
        "subcategory": "       ",
        "ingredient1": "Clarithromycin",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "69",
        "pharma": "Leeford",
        "undefined": " "
    },
    {
        "brandName": "Piprataz inj",
        "category": "Antibiotic",
        "subcategory": "       ",
        "ingredient1": "Piperacillin",
        "ingredient2": "Tazobactum",
        "unit": "Injection",
        "ptr": "99",
        "pharma": "Abbott",
        "undefined": " "
    },
    {
        "brandName": "Alcid MPS",
        "category": "Antacid",
        "subcategory": "Antiflatulent",
        "ingredient1": "Aluminium",
        "ingredient2": "Magnesium, simethicone",
        "unit": "Syrup",
        "ptr": "21.86",
        "pharma": "ALE",
        "undefined": " "
    },
    {
        "brandName": "NS 100 ml",
        "category": "Fluid",
        "subcategory": "       ",
        "ingredient1": "Normal saline 0.9%",
        "ingredient2": " ",
        "unit": "Bottle",
        "ptr": "11.5",
        "pharma": "Alkem",
        "undefined": " "
    },
    {
        "brandName": "Eterna 2 ml",
        "category": "Antiemetic",
        "subcategory": "       ",
        "ingredient1": "Ondansetron",
        "ingredient2": " ",
        "unit": "Injection",
        "ptr": "9.5",
        "pharma": "Blue Cross",
        "undefined": " "
    },
    {
        "brandName": "Pantosec D SR",
        "category": "Antacid",
        "subcategory": "       ",
        "ingredient1": "Pantoprazole",
        "ingredient2": "Domperidone",
        "unit": "Capsule",
        "ptr": "33.4",
        "pharma": "CIPLA",
        "undefined": " "
    },
    {
        "brandName": "Tetanus toxoid",
        "category": "Vaccine",
        "subcategory": "       ",
        "ingredient1": "TT",
        "ingredient2": " ",
        "unit": "Injection",
        "ptr": "9.2",
        "pharma": "DAN",
        "undefined": " "
    },
    {
        "brandName": "Eldervit Syp 200",
        "category": "Supplement",
        "subcategory": "       ",
        "ingredient1": " ",
        "ingredient2": " ",
        "unit": " ",
        "ptr": "20",
        "pharma": "ELDER",
        "undefined": " "
    },
    {
        "brandName": "Eldervit Syp 100",
        "category": "Supplement",
        "subcategory": "       ",
        "ingredient1": " ",
        "ingredient2": " ",
        "unit": " ",
        "ptr": "11.5",
        "pharma": "ELDER",
        "undefined": " "
    },
    {
        "brandName": "Broncofil-N",
        "category": "Mucolytic",
        "subcategory": "Bronchodilator",
        "ingredient1": "Acebrophylline",
        "ingredient2": "Acetylcysteine",
        "unit": "Tablet",
        "ptr": "82.2",
        "pharma": "Leeford",
        "undefined": " "
    },
    {
        "brandName": "Lee biotic Cap",
        "category": "    ",
        "subcategory": "       ",
        "ingredient1": " ",
        "ingredient2": " ",
        "unit": "Capsule",
        "ptr": "29.4",
        "pharma": "Leeford",
        "undefined": " "
    },
    {
        "brandName": "Benogermina Respule",
        "category": "Probiotic",
        "subcategory": "       ",
        "ingredient1": "Bacillus Clausii",
        "ingredient2": " ",
        "unit": "Respule",
        "ptr": "12.94",
        "pharma": "OT/Nectar",
        "undefined": " "
    },
    {
        "brandName": "Leevron",
        "category": "    ",
        "subcategory": "       ",
        "ingredient1": " ",
        "ingredient2": " ",
        "unit": "Gel",
        "ptr": "13",
        "pharma": "OT/Nectar",
        "undefined": " "
    },
    {
        "brandName": "Lycopen Red",
        "category": "Supplement",
        "subcategory": "       ",
        "ingredient1": "Lycopene",
        "ingredient2": " ",
        "unit": "Syrup",
        "ptr": "22",
        "pharma": "OT/Nectar",
        "undefined": " "
    },
    {
        "brandName": "Budefex 2 ml",
        "category": "Bronchodilator",
        "subcategory": "       ",
        "ingredient1": "Budesol",
        "ingredient2": " ",
        "unit": "respule",
        "ptr": "265.65",
        "pharma": "RANBAXY",
        "undefined": " "
    },
    {
        "brandName": "Histac MPS Mint",
        "category": "Antacid",
        "subcategory": "Antiflatulent",
        "ingredient1": "Aluminium",
        "ingredient2": "Magnesium, simethicone",
        "unit": "Syrup",
        "ptr": "27.6",
        "pharma": "RANBAXY",
        "undefined": " "
    },
    {
        "brandName": "Ecoryl LS",
        "category": "Cough syrup",
        "subcategory": "Bronchodilator, mucolytic",
        "ingredient1": "Levosalbutamol",
        "ingredient2": "Ambroxol, guaiphenesin, menthol",
        "unit": "Syrup",
        "ptr": "24.84",
        "pharma": "TARUN",
        "undefined": " "
    },
    {
        "brandName": "Panzof IV",
        "category": "Antacid",
        "subcategory": "PPI",
        "ingredient1": "Pantoprazole",
        "ingredient2": " ",
        "unit": "Injection",
        "ptr": "10",
        "pharma": "TARUN",
        "undefined": " "
    },
    {
        "brandName": "Tazilin",
        "category": "Antibiotic",
        "subcategory": "       ",
        "ingredient1": "Piperacillin",
        "ingredient2": "Tazobactum",
        "unit": "Injection",
        "ptr": "97.75",
        "pharma": "Zydus",
        "undefined": " "
    },
    {
        "brandName": "Alivia 4G",
        "category": "Supplement",
        "subcategory": "       ",
        "ingredient1": "Omega 3",
        "ingredient2": "Gingko biloba, ginseng, green tea",
        "unit": "Tablet",
        "ptr": "134.24",
        "pharma": "Zed/Redvia",
        "undefined": " "
    },
    {
        "brandName": "Uticam",
        "category": "Supplement",
        "subcategory": "UTI supplement",
        "ingredient1": "Cranberry",
        "ingredient2": "D Mannose, Potassium magnesium citrate",
        "unit": "Powder",
        "ptr": "32.85",
        "pharma": "Trumac",
        "undefined": " "
    },
    {
        "brandName": "Larzon",
        "category": "Supplement",
        "subcategory": "Gynec",
        "ingredient1": "L-Arginine",
        "ingredient2": "Proanthocyanin",
        "unit": "Powder",
        "ptr": "34.74",
        "pharma": "Crinova",
        "undefined": " "
    },
    {
        "brandName": "Myorin tab",
        "category": "Supplement",
        "subcategory": "Gynec",
        "ingredient1": "Myo inositol",
        "ingredient2": "D chiro inositol, chromium, vit D3",
        "unit": "Tablet",
        "ptr": "125.08",
        "pharma": "Crinova",
        "undefined": " "
    },
    {
        "brandName": "Arzistal",
        "category": "Supplement",
        "subcategory": "Gynec",
        "ingredient1": "L-Arginine",
        "ingredient2": "Zinc sulphate, folic acid",
        "unit": "Powder",
        "ptr": " ",
        "pharma": "Leeford",
        "undefined": " "
    },
    {
        "brandName": "Zilargyn-Z5",
        "category": "Supplement",
        "subcategory": "Gynec",
        "ingredient1": "L-Arginine",
        "ingredient2": " ",
        "unit": "Powder",
        "ptr": " ",
        "pharma": "Bharat Serum",
        "undefined": " "
    },
    {
        "brandName": "Dinolex-2",
        "category": "Supplement",
        "subcategory": "Gynec",
        "ingredient1": "Dienogest",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "435.62",
        "pharma": "Trumac",
        "undefined": " "
    },
    {
        "brandName": "Cysvia 35",
        "category": "Hormones",
        "subcategory": "Gynec",
        "ingredient1": "Ethinylestradiol",
        "ingredient2": "Cyproterone",
        "unit": "Tablet",
        "ptr": "226.96",
        "pharma": "Osiante",
        "undefined": " "
    },
    {
        "brandName": "Drosmyra",
        "category": "Hormones",
        "subcategory": "Gynec",
        "ingredient1": "Drosperinone",
        "ingredient2": "Ethinylestradiol",
        "unit": "Tablet",
        "ptr": "399",
        "pharma": "Osiante",
        "undefined": " "
    },
    {
        "brandName": "Larzon",
        "category": "Supplement",
        "subcategory": "Gynec",
        "ingredient1": "L-Arginine",
        "ingredient2": "Proanthocyanin",
        "unit": "Powder",
        "ptr": "41.69",
        "pharma": "Crinova",
        "undefined": " "
    },
    {
        "brandName": "Paning DSR",
        "category": "Antacid",
        "subcategory": "       ",
        "ingredient1": "Pantoprazole",
        "ingredient2": "Domperidone",
        "unit": "Capsule",
        "ptr": "60.82",
        "pharma": "Celife",
        "undefined": " "
    },
    {
        "brandName": "Paning 40",
        "category": "Antacid",
        "subcategory": "       ",
        "ingredient1": "Pantoprazole",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "42.93",
        "pharma": "Celife",
        "undefined": " "
    },
    {
        "brandName": "ODHIST M",
        "category": "Antihistamine",
        "subcategory": "       ",
        "ingredient1": "Levocetirizine",
        "ingredient2": "Montelukast",
        "unit": "Tablet",
        "ptr": "57.84",
        "pharma": "Celife",
        "undefined": " "
    },
    {
        "brandName": "Defgate-6",
        "category": "Corticosteroid",
        "subcategory": "       ",
        "ingredient1": "Deflazacort",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": "54.64",
        "pharma": "Celife",
        "undefined": " "
    },
    {
        "brandName": "Zo D drops",
        "category": "    ",
        "subcategory": "       ",
        "ingredient1": " ",
        "ingredient2": " ",
        "unit": "Syrup",
        "ptr": "19.86",
        "pharma": "FDC",
        "undefined": " "
    },
    {
        "brandName": "Duvadilan",
        "category": "    ",
        "subcategory": "       ",
        "ingredient1": " ",
        "ingredient2": " ",
        "unit": " ",
        "ptr": " ",
        "pharma": " ",
        "undefined": " "
    },
    {
        "brandName": "Penomclav 500+125",
        "category": "Antibiotic",
        "subcategory": "Internal Medicine",
        "ingredient1": "Coamoxiclav",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": " ",
        "pharma": "Apostle Remedies",
        "undefined": " "
    },
    {
        "brandName": "Penomclav 200+28.5",
        "category": "Antibiotic",
        "subcategory": "Internal Medicine",
        "ingredient1": "Coamoxiclav",
        "ingredient2": "30 ml",
        "unit": "Syrup",
        "ptr": " ",
        "pharma": "Apostle Remedies",
        "undefined": " "
    },
    {
        "brandName": "Penomclav 200+28.5",
        "category": "Antibiotic",
        "subcategory": "Internal Medicine",
        "ingredient1": "Coamoxiclav",
        "ingredient2": "60 ml",
        "unit": "Syrup",
        "ptr": " ",
        "pharma": "Apostle Remedies",
        "undefined": " "
    },
    {
        "brandName": "Penomclav 400 + 57",
        "category": "Antibiotic",
        "subcategory": "Internal Medicine",
        "ingredient1": "Coamoxiclav",
        "ingredient2": "30 ml",
        "unit": "Syrup",
        "ptr": " ",
        "pharma": "Apostle Remedies",
        "undefined": " "
    },
    {
        "brandName": "Penomclav 400 + 57",
        "category": "Antibiotic",
        "subcategory": "Internal Medicine",
        "ingredient1": "Coamoxiclav",
        "ingredient2": "60 ml",
        "unit": "Syrup",
        "ptr": " ",
        "pharma": "Apostle Remedies",
        "undefined": " "
    },
    {
        "brandName": "Penom 125",
        "category": "Antibiotic",
        "subcategory": "Internal Medicine",
        "ingredient1": "Amoxycillin",
        "ingredient2": " ",
        "unit": "Tablet",
        "ptr": " ",
        "pharma": "Apostle Remedies",
        "undefined": " "
    }
]
