export const data = [
 {
   sr_no: 1,
   brand_name: "Bioviz P Cap",
   category: "Probiotic",
   sub_category: "",
   ingredient_1: "Lactobacillus",
   ingredient_2: "Bifidobacterium",
   unit: "Capsule",
   ptr: 94.92,
   gst_percent: "0%",
   gst_amount: 0,
   total_w_gst: 94.92,
   mrp: 148,
   pharma: "Medivista",
   stockist: "H and H",
   scm: "10+2",
   last_ordered_quantity: 10,
   last_ordered_date: "02/11/22",
   field18: "20+4",
   field19: "10/10/22",
   field20: "",
   field21: ""
 },
 {
   sr_no: 2,
   brand_name: "Cetfran Syp",
   category: "Cough syrup",
   sub_category: "",
   ingredient_1: "Dextromethorphan",
   ingredient_2: "Phenlyephrine",
   unit: "Syrup",
   ptr: 58.57,
   gst_percent: "12%",
   gst_amount: 7.03,
   total_w_gst: 65.6,
   mrp: 82,
   pharma: "Irene",
   stockist: "H and H",
   scm: "10+2",
   last_ordered_quantity: 10,
   last_ordered_date: "02/11/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 3,
   brand_name: "Cefmixet 200",
   category: "Antibiotic",
   sub_category: "Cephalosporin",
   ingredient_1: "Cefpodoxime",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 142.86,
   gst_percent: "12%",
   gst_amount: 17.14,
   total_w_gst: 160,
   mrp: 200,
   pharma: "Irene",
   stockist: "H and H",
   scm: "10+2",
   last_ordered_quantity: 10,
   last_ordered_date: "04/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 4,
   brand_name: "Cefmixet Dry syrup",
   category: "Antibiotic",
   sub_category: "Cephalosporin",
   ingredient_1: "Cefpodoxime",
   ingredient_2: "",
   unit: "Syrup",
   ptr: 60.71,
   gst_percent: "12%",
   gst_amount: 7.29,
   total_w_gst: 68,
   mrp: 85,
   pharma: "Irene",
   stockist: "H and H",
   scm: "5+1",
   last_ordered_quantity: 5,
   last_ordered_date: "04/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 5,
   brand_name: "Diclomide gel",
   category: "Analgesic",
   sub_category: "",
   ingredient_1: "Diclofenac",
   ingredient_2: "methyl, linseed oil, menthol",
   unit: "Gel",
   ptr: 53.57,
   gst_percent: "12%",
   gst_amount: 6.43,
   total_w_gst: 60,
   mrp: 75,
   pharma: "Irene",
   stockist: "H and H",
   scm: "5+1",
   last_ordered_quantity: 5,
   last_ordered_date: "04/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 6,
   brand_name: "Irethro 250",
   category: "Antibiotic",
   sub_category: "",
   ingredient_1: "Azithromycin",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 83.18,
   gst_percent: "12%",
   gst_amount: 9.98,
   total_w_gst: 93.16,
   mrp: 117.5,
   pharma: "Irene",
   stockist: "H and H",
   scm: "30+6",
   last_ordered_quantity: 30,
   last_ordered_date: "04/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 7,
   brand_name: "Irecef 500",
   category: "Antibiotic",
   sub_category: "Cephalosporin",
   ingredient_1: "Cefuroxime",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 407.14,
   gst_percent: "12%",
   gst_amount: 48.86,
   total_w_gst: 456,
   mrp: 570,
   pharma: "Irene",
   stockist: "H and H",
   scm: "5+1",
   last_ordered_quantity: 9,
   last_ordered_date: "04/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 8,
   brand_name: "Iremox CA",
   category: "Antibiotic",
   sub_category: "",
   ingredient_1: "Amoxycillin Clavulanic acid",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 85.71,
   gst_percent: "12%",
   gst_amount: 10.29,
   total_w_gst: 96,
   mrp: 120,
   pharma: "Irene",
   stockist: "H and H",
   scm: "20+4",
   last_ordered_quantity: 20,
   last_ordered_date: "04/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 9,
   brand_name: "Irethro 500",
   category: "Antibiotic",
   sub_category: "",
   ingredient_1: "Azithromycin",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 50.71,
   gst_percent: "12%",
   gst_amount: 6.09,
   total_w_gst: 56.8,
   mrp: 71,
   pharma: "Irene",
   stockist: "H and H",
   scm: "20+4",
   last_ordered_quantity: 20,
   last_ordered_date: "04/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 10,
   brand_name: "Irime- LBTAB",
   category: "Antibiotic",
   sub_category: "Cephalosporin",
   ingredient_1: "Cefixime",
   ingredient_2: "Lactic acid",
   unit: "Tablet",
   ptr: 107.14,
   gst_percent: "12%",
   gst_amount: 12.86,
   total_w_gst: 120,
   mrp: 150,
   pharma: "Irene",
   stockist: "H and H",
   scm: "20+4",
   last_ordered_quantity: 23,
   last_ordered_date: "04/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 11,
   brand_name: "Lycolin",
   category: "Supplement",
   sub_category: "",
   ingredient_1: "Lycopene, copper, selenium, iodine, zinc",
   ingredient_2: "Cyanacobalamin, folic acid, nicotinamide",
   unit: "Syrup",
   ptr: 107.14,
   gst_percent: "12%",
   gst_amount: 12.86,
   total_w_gst: 120,
   mrp: 150,
   pharma: "Irene",
   stockist: "H and H",
   scm: "5+1",
   last_ordered_quantity: 5,
   last_ordered_date: "04/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 12,
   brand_name: "Ricob 90",
   category: "Analgesic",
   sub_category: "",
   ingredient_1: "Etorocoxib",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 70,
   gst_percent: "12%",
   gst_amount: 8.4,
   total_w_gst: 78.4,
   mrp: 98,
   pharma: "Irene",
   stockist: "H and H",
   scm: "10+2",
   last_ordered_quantity: 10,
   last_ordered_date: "04/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 13,
   brand_name: "Kuflax",
   category: "Cough syrup",
   sub_category: "",
   ingredient_1: "Terbutaline",
   ingredient_2: "Ambroxol, guaiphenesin, menthol",
   unit: "Syrup",
   ptr: 60.71,
   gst_percent: "12%",
   gst_amount: 7.29,
   total_w_gst: 68,
   mrp: 85,
   pharma: "Medivista",
   stockist: "H and H",
   scm: "10+2",
   last_ordered_quantity: 10,
   last_ordered_date: "04/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 14,
   brand_name: "Shurecal",
   category: "Supplement",
   sub_category: "Mineral",
   ingredient_1: "Calcium",
   ingredient_2: "",
   unit: "Suspension",
   ptr: 70,
   gst_percent: "12%",
   gst_amount: 8.4,
   total_w_gst: 78.4,
   mrp: 98,
   pharma: "AIS",
   stockist: "H and H",
   scm: "10+2",
   last_ordered_quantity: 10,
   last_ordered_date: "10/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 15,
   brand_name: "Brutraxin D",
   category: "Analgesic",
   sub_category: "",
   ingredient_1: "Trypsin, bromolexin, rutoside, diclofenac",
   ingredient_2: "Diclofenac",
   unit: "Tablet",
   ptr: 142.14,
   gst_percent: "12%",
   gst_amount: 17.06,
   total_w_gst: 159.2,
   mrp: 199,
   pharma: "Irene",
   stockist: "H and H",
   scm: "20+4",
   last_ordered_quantity: 20,
   last_ordered_date: "10/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 16,
   brand_name: "Mefeliton",
   category: "Analgesic",
   sub_category: "",
   ingredient_1: "Mefenamic acid",
   ingredient_2: "Dicyclomine",
   unit: "Tablet",
   ptr: 28.57,
   gst_percent: "12%",
   gst_amount: 3.43,
   total_w_gst: 32,
   mrp: 40,
   pharma: "Irene",
   stockist: "H and H",
   scm: "20+2",
   last_ordered_quantity: 20,
   last_ordered_date: "10/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 17,
   brand_name: "Cetjoint K27",
   category: "Supplement",
   sub_category: "Mineral",
   ingredient_1: "Calcitriol",
   ingredient_2: "Calcium carbonate, vitamin K2-7",
   unit: "Capsule",
   ptr: 121.43,
   gst_percent: "12%",
   gst_amount: 14.57,
   total_w_gst: 136,
   mrp: 170,
   pharma: "Leeford",
   stockist: "H and H",
   scm: "10+2",
   last_ordered_quantity: 10,
   last_ordered_date: "10/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 18,
   brand_name: "Glipiride 1",
   category: "Anti-Diabetic",
   sub_category: "",
   ingredient_1: "Glimepiride",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 28.79,
   gst_percent: "12%",
   gst_amount: 3.45,
   total_w_gst: 32.24,
   mrp: 40.3,
   pharma: "Leeford",
   stockist: "H and H",
   scm: "20+4",
   last_ordered_quantity: 20,
   last_ordered_date: "10/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 19,
   brand_name: "Flexen - OS",
   category: "Antacid",
   sub_category: "aluminium hydroxide and a sulphate derivative of sucrose.",
   ingredient_1: "sucralfate",
   ingredient_2: "Oxetacaine",
   unit: "Syrup",
   ptr: 85.71,
   gst_percent: "",
   gst_amount: 0,
   total_w_gst: 85.71,
   mrp: 120,
   pharma: "Medivista",
   stockist: "H and H",
   scm: "10+1",
   last_ordered_quantity: 10,
   last_ordered_date: "10/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 20,
   brand_name: "Moxyviz 375",
   category: "Antibiotic",
   sub_category: "",
   ingredient_1: "Amoxycillin Clavulanic acid",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 85.71,
   gst_percent: "",
   gst_amount: 0,
   total_w_gst: 85.71,
   mrp: 120,
   pharma: "Medivista",
   stockist: "H and H",
   scm: "30+6",
   last_ordered_quantity: 30,
   last_ordered_date: "10/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 21,
   brand_name: "Pregaviz-M",
   category: "Analgesic",
   sub_category: "anticonvulsant, analgesic and anxiolytic",
   ingredient_1: "Pregabalin",
   ingredient_2: "Methylcobalamin",
   unit: "Tablet",
   ptr: 89.28,
   gst_percent: "",
   gst_amount: 0,
   total_w_gst: 89.28,
   mrp: 125,
   pharma: "Medivista",
   stockist: "H and H",
   scm: "20+4",
   last_ordered_quantity: 20,
   last_ordered_date: "10/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 22,
   brand_name: "Lufee cream 30 gm",
   category: "Antifungal",
   sub_category: "",
   ingredient_1: "Luliconazole",
   ingredient_2: "",
   unit: "Cream",
   ptr: 196.43,
   gst_percent: "12%",
   gst_amount: 23.57,
   total_w_gst: 220,
   mrp: 275,
   pharma: "TAR",
   stockist: "H and H",
   scm: "10+2",
   last_ordered_quantity: 10,
   last_ordered_date: "10/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 23,
   brand_name: "Pantozee inj",
   category: "Antacid",
   sub_category: "PPI",
   ingredient_1: "Pantoprazole",
   ingredient_2: "",
   unit: "Injection",
   ptr: 35.71,
   gst_percent: "12%",
   gst_amount: 4.29,
   total_w_gst: 40,
   mrp: 50,
   pharma: "ZEE",
   stockist: "H and H",
   scm: "50+10",
   last_ordered_quantity: 10,
   last_ordered_date: "20/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 24,
   brand_name: "Smithcee plus",
   category: "Supplement",
   sub_category: "Vitamin",
   ingredient_1: "Vitamin C",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 42.86,
   gst_percent: "12%",
   gst_amount: 5.14,
   total_w_gst: 48,
   mrp: 60,
   pharma: "GLE",
   stockist: "H and H",
   scm: "20+4",
   last_ordered_quantity: 20,
   last_ordered_date: "20/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 25,
   brand_name: "Bioviz sachet",
   category: "Probiotic",
   sub_category: "",
   ingredient_1: "",
   ingredient_2: "",
   unit: "Powder",
   ptr: 18.98,
   gst_percent: "",
   gst_amount: 0,
   total_w_gst: 18.98,
   mrp: 28,
   pharma: "Medivista",
   stockist: "H and H",
   scm: "40+8",
   last_ordered_quantity: 40,
   last_ordered_date: "20/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 26,
   brand_name: "Caltrorin Cal-D3",
   category: "Supplement",
   sub_category: "",
   ingredient_1: "Calcium carbonate",
   ingredient_2: "calcitriol, omega 3, methylcobalamin, boron, folic acid",
   unit: "Capsule",
   ptr: 157.14,
   gst_percent: "12%",
   gst_amount: 18.86,
   total_w_gst: 176,
   mrp: 220,
   pharma: "Irene",
   stockist: "H and H",
   scm: "20+4",
   last_ordered_quantity: 20,
   last_ordered_date: "20/09/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 27,
   brand_name: "Irenac MR",
   category: "Analgesic",
   sub_category: "Muscle Relaxant",
   ingredient_1: "Aceclofenac",
   ingredient_2: "Paracetamol, chlorzoxazone",
   unit: "Tablet",
   ptr: 57.14,
   gst_percent: "12%",
   gst_amount: 6.86,
   total_w_gst: 64,
   mrp: 80,
   pharma: "Irene",
   stockist: "H and H",
   scm: "50+10",
   last_ordered_quantity: 50,
   last_ordered_date: "20/09/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 28,
   brand_name: "Irento-40",
   category: "Antacid",
   sub_category: "PPI",
   ingredient_1: "Pantoprazole",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 42.86,
   gst_percent: "12%",
   gst_amount: 5.14,
   total_w_gst: 48,
   mrp: 60,
   pharma: "Irene",
   stockist: "H and H",
   scm: "50+10",
   last_ordered_quantity: 50,
   last_ordered_date: "20/09/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 29,
   brand_name: "Proteadd-Plus",
   category: "Supplement",
   sub_category: "Protein powder",
   ingredient_1: "",
   ingredient_2: "",
   unit: "Powder",
   ptr: 186.44,
   gst_percent: "18%",
   gst_amount: 33.56,
   total_w_gst: 220,
   mrp: 275,
   pharma: "Irene",
   stockist: "H and H",
   scm: "15+3",
   last_ordered_quantity: 15,
   last_ordered_date: "15/09/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 30,
   brand_name: "Livertine XL",
   category: "Supplement",
   sub_category: "Ayurvedic",
   ingredient_1: "",
   ingredient_2: "",
   unit: "Syrup",
   ptr: 85.72,
   gst_percent: "12%",
   gst_amount: 10.29,
   total_w_gst: 96.01,
   mrp: 120,
   pharma: "Irene",
   stockist: "H and H",
   scm: "20+4",
   last_ordered_quantity: 20,
   last_ordered_date: "17/09/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 31,
   brand_name: "Pirolacin DT",
   category: "Analgesic",
   sub_category: "",
   ingredient_1: "Piroxicam",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 27.07,
   gst_percent: "12%",
   gst_amount: 3.25,
   total_w_gst: 30.32,
   mrp: 37.9,
   pharma: "Irene",
   stockist: "H and H",
   scm: "0",
   last_ordered_quantity: 23,
   last_ordered_date: "26/09/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 32,
   brand_name: "Kalciviz-CT",
   category: "Supplement",
   sub_category: "",
   ingredient_1: "Calcitriol",
   ingredient_2: "Calcium Citrate maleate, zinc, magnesium oxide",
   unit: "Capsule",
   ptr: 85.71,
   gst_percent: "12%",
   gst_amount: 10.29,
   total_w_gst: 96,
   mrp: 120,
   pharma: "Medivista",
   stockist: "H and H",
   scm: "10+2",
   last_ordered_quantity: 8,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 33,
   brand_name: "Citrol D3",
   category: "Supplement",
   sub_category: "",
   ingredient_1: "Vitamin D3",
   ingredient_2: "",
   unit: "Capsule",
   ptr: 85.71,
   gst_percent: "12%",
   gst_amount: 10.29,
   total_w_gst: 96,
   mrp: 120,
   pharma: "Medivista",
   stockist: "H and H",
   scm: "10+2",
   last_ordered_quantity: 28,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 34,
   brand_name: "Citrol D3",
   category: "Supplement",
   sub_category: "",
   ingredient_1: "Vitamin D3",
   ingredient_2: "",
   unit: "Powder",
   ptr: 20.33,
   gst_percent: "18%",
   gst_amount: 3.66,
   total_w_gst: 23.99,
   mrp: 30,
   pharma: "Medivista",
   stockist: "H and H",
   scm: "10+2",
   last_ordered_quantity: 13,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 35,
   brand_name: "Meditron med",
   category: "Antiemetic",
   sub_category: "",
   ingredient_1: "Ondansetron",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 37.14,
   gst_percent: "12%",
   gst_amount: 4.46,
   total_w_gst: 41.6,
   mrp: 52,
   pharma: "Medivista",
   stockist: "H and H",
   scm: "10+2",
   last_ordered_quantity: 8,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 36,
   brand_name: "Hyrox-25",
   category: "Antihistamine",
   sub_category: "",
   ingredient_1: "Hydroxyzine",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 25,
   gst_percent: "12%",
   gst_amount: 3,
   total_w_gst: 28,
   mrp: 35,
   pharma: "Medivista",
   stockist: "H and H",
   scm: "10+2",
   last_ordered_quantity: 9,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 37,
   brand_name: "Acenex Plus",
   category: "Analgesic",
   sub_category: "",
   ingredient_1: "",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 12,
   gst_percent: "12%",
   gst_amount: 1.44,
   total_w_gst: 13.44,
   mrp: 44,
   pharma: "Bione",
   stockist: "Abhijeet pharma",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "13/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 38,
   brand_name: "MDIC gel 30 gm",
   category: "Analgesic",
   sub_category: "",
   ingredient_1: "Diclofenac",
   ingredient_2: "Menthol",
   unit: "Gel",
   ptr: 18,
   gst_percent: "12%",
   gst_amount: 2.16,
   total_w_gst: 20.16,
   mrp: 85,
   pharma: "MRG",
   stockist: "Abhijeet pharma",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "13/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 39,
   brand_name: "Omcure 20 mg",
   category: "Antacid",
   sub_category: "",
   ingredient_1: "Omeprazole",
   ingredient_2: "",
   unit: "Capsule",
   ptr: 10,
   gst_percent: "12%",
   gst_amount: 1.2,
   total_w_gst: 11.2,
   mrp: 27,
   pharma: "FINE",
   stockist: "Abhijeet pharma",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "13/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 40,
   brand_name: "Pantonext 40mg",
   category: "Antacid",
   sub_category: "PPI",
   ingredient_1: "Pantoprazole",
   ingredient_2: "",
   unit: "Injection",
   ptr: 12,
   gst_percent: "12%",
   gst_amount: 1.44,
   total_w_gst: 13.44,
   mrp: 59,
   pharma: "Bione",
   stockist: "Abhijeet pharma",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "13/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 41,
   brand_name: "Cacitate Plus",
   category: "Supplement",
   sub_category: "",
   ingredient_1: "Calcium 100",
   ingredient_2: "Vit D3 200",
   unit: "Syrup",
   ptr: 14,
   gst_percent: "12%",
   gst_amount: 1.68,
   total_w_gst: 15.68,
   mrp: 56,
   pharma: "FINE",
   stockist: "Abhijeet pharma",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "13/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 42,
   brand_name: "Zincolive",
   category: "Supplement",
   sub_category: "",
   ingredient_1: "",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 26,
   gst_percent: "18%",
   gst_amount: 4.68,
   total_w_gst: 30.68,
   mrp: 110,
   pharma: "Iheal",
   stockist: "Abhijeet pharma",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "13/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 43,
   brand_name: "Nextbest Forte",
   category: "Supplement",
   sub_category: "zinc",
   ingredient_1: "Calcium pantothenate",
   ingredient_2: "calcium, copper, magnesium, manganese, zinc 50 mg, folic acid, iodine, niacinamide, phosphorus, Vitamin A, et",
   unit: "Capsule",
   ptr: 15,
   gst_percent: "12%",
   gst_amount: 1.8,
   total_w_gst: 16.8,
   mrp: 49.5,
   pharma: "Bione",
   stockist: "Abhijeet pharma",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "13/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 44,
   brand_name: "Alext",
   category: "Antihistamine",
   sub_category: "",
   ingredient_1: "Levocetirizine",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 6,
   gst_percent: "12%",
   gst_amount: 0.72,
   total_w_gst: 6.72,
   mrp: 29.5,
   pharma: "Bione",
   stockist: "Abhijeet pharma",
   scm: "0",
   last_ordered_quantity: 20,
   last_ordered_date: "13/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 45,
   brand_name: "Ferotex-FA Plus",
   category: "Supplement",
   sub_category: "",
   ingredient_1: "",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 17,
   gst_percent: "12%",
   gst_amount: 2.04,
   total_w_gst: 19.04,
   mrp: 99,
   pharma: "Bione",
   stockist: "Abhijeet pharma",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "13/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 46,
   brand_name: "Coldmart-P",
   category: "Antihistamine",
   sub_category: "Analgesic antipyretic",
   ingredient_1: "Paracetamol",
   ingredient_2: "Phenylephrine, diphenhydramine",
   unit: "Tablet",
   ptr: 12.5,
   gst_percent: "12%",
   gst_amount: 1.5,
   total_w_gst: 14,
   mrp: 65,
   pharma: "IHeal",
   stockist: "Abhijeet pharma",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "13/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 47,
   brand_name: "Lulinext",
   category: "Antifungal",
   sub_category: "",
   ingredient_1: "Luliconazole",
   ingredient_2: "",
   unit: "Ointment",
   ptr: 45,
   gst_percent: "12%",
   gst_amount: 5.4,
   total_w_gst: 50.4,
   mrp: 190,
   pharma: "Bione",
   stockist: "Abhijeet pharma",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "13/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 48,
   brand_name: "Lorid tab",
   category: "Antihistamine",
   sub_category: "",
   ingredient_1: "Loratidine",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 39.52,
   gst_percent: "12%",
   gst_amount: 4.74,
   total_w_gst: 44.26,
   mrp: 54,
   pharma: "FINE",
   stockist: "Abhijeet pharma",
   scm: "10+2",
   last_ordered_quantity: 10,
   last_ordered_date: "19/07/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 49,
   brand_name: "Ferotex",
   category: "Supplement",
   sub_category: "Iron",
   ingredient_1: "Ferrous",
   ingredient_2: "",
   unit: "Syrup",
   ptr: 72.47,
   gst_percent: "12%",
   gst_amount: 8.7,
   total_w_gst: 81.17,
   mrp: 99,
   pharma: "Bione",
   stockist: "Abhijeet pharma",
   scm: "10+2",
   last_ordered_quantity: 10,
   last_ordered_date: "19/07/22",
   field18: "25",
   field19: "22/08/22",
   field20: "",
   field21: ""
 },
 {
   sr_no: 50,
   brand_name: "Glipvil M 1000",
   category: "Anti-Diabetic",
   sub_category: "",
   ingredient_1: "Metformin",
   ingredient_2: "Vildagliptin",
   unit: "Tablet",
   ptr: 68.07,
   gst_percent: "12%",
   gst_amount: 8.17,
   total_w_gst: 76.24,
   mrp: 93,
   pharma: "FINE",
   stockist: "Abhijeet pharma",
   scm: "25+5",
   last_ordered_quantity: 25,
   last_ordered_date: "22/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 51,
   brand_name: "Glipvil M 500",
   category: "Anti-Diabetic",
   sub_category: "",
   ingredient_1: "Metformin",
   ingredient_2: "Vildagliptin",
   unit: "Tablet",
   ptr: 54.9,
   gst_percent: "12%",
   gst_amount: 6.59,
   total_w_gst: 61.49,
   mrp: 75,
   pharma: "FINE",
   stockist: "Abhijeet pharma",
   scm: "25+5",
   last_ordered_quantity: 25,
   last_ordered_date: "22/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 52,
   brand_name: "Mefmid D",
   category: "Analgesic",
   sub_category: "Antispasmodic",
   ingredient_1: "Mefenamic acid",
   ingredient_2: "Drotaverine",
   unit: "Tablet",
   ptr: 60,
   gst_percent: "0%",
   gst_amount: 0,
   total_w_gst: 60,
   mrp: 75,
   pharma: "Tenwel",
   stockist: "Lifeline",
   scm: "10+2",
   last_ordered_quantity: 10,
   last_ordered_date: "08/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 53,
   brand_name: "Sedoxe-200",
   category: "Antibiotic",
   sub_category: "Cephalosporin",
   ingredient_1: "Cefpodoxime",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 192,
   gst_percent: "0%",
   gst_amount: 0,
   total_w_gst: 192,
   mrp: 240,
   pharma: "Tenwel",
   stockist: "Lifeline",
   scm: "20+4",
   last_ordered_quantity: 20,
   last_ordered_date: "08/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 54,
   brand_name: "Neuroten N",
   category: "Analgesic",
   sub_category: "",
   ingredient_1: "",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 68,
   gst_percent: "0%",
   gst_amount: 0,
   total_w_gst: 68,
   mrp: 85,
   pharma: "Tenwel",
   stockist: "Lifeline",
   scm: "10+2",
   last_ordered_quantity: 10,
   last_ordered_date: "08/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 55,
   brand_name: "Sedoxe-50",
   category: "Antibiotic",
   sub_category: "Cephalosporin",
   ingredient_1: "Cefpodoxime",
   ingredient_2: "",
   unit: "Syrup",
   ptr: 76,
   gst_percent: "0%",
   gst_amount: 0,
   total_w_gst: 76,
   mrp: 95,
   pharma: "Tenwel",
   stockist: "Lifeline",
   scm: "5+1",
   last_ordered_quantity: 5,
   last_ordered_date: "08/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 56,
   brand_name: "Silyplex-L",
   category: "Supplement",
   sub_category: "",
   ingredient_1: "Silymarin",
   ingredient_2: "Thiamine, Vit B12",
   unit: "Syrup",
   ptr: 116,
   gst_percent: "0%",
   gst_amount: 0,
   total_w_gst: 116,
   mrp: 145,
   pharma: "Tenwel",
   stockist: "Lifeline",
   scm: "5+1",
   last_ordered_quantity: 5,
   last_ordered_date: "08/10/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 57,
   brand_name: "L-hist mont Fx",
   category: "Antihistamine",
   sub_category: "",
   ingredient_1: "",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 48.93,
   gst_percent: "12%",
   gst_amount: 5.87,
   total_w_gst: 54.8,
   mrp: 195,
   pharma: "Alkem",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "29/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 58,
   brand_name: "NS 100 ml",
   category: "Fluid",
   sub_category: "",
   ingredient_1: "Normal saline 0.9%",
   ingredient_2: "",
   unit: "Bottle",
   ptr: 11.5,
   gst_percent: "12%",
   gst_amount: 1.38,
   total_w_gst: 12.88,
   mrp: 17.62,
   pharma: "Alkem",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 100,
   last_ordered_date: "29/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 59,
   brand_name: "Cipcal 500",
   category: "Supplement",
   sub_category: "",
   ingredient_1: "Calcium",
   ingredient_2: "Vit D3",
   unit: "Tablet",
   ptr: 17.22,
   gst_percent: "12%",
   gst_amount: 2.07,
   total_w_gst: 19.29,
   mrp: 86.5,
   pharma: "CIPLA",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "29/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 60,
   brand_name: "Pantin IV",
   category: "Antacid",
   sub_category: "PPI",
   ingredient_1: "Pantoprazole",
   ingredient_2: "",
   unit: "Injection",
   ptr: 13.4,
   gst_percent: "12%",
   gst_amount: 1.61,
   total_w_gst: 15.01,
   mrp: 54.5,
   pharma: "HETRO",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "29/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 61,
   brand_name: "DOO CLAV 30 ml",
   category: "Antibiotic",
   sub_category: "",
   ingredient_1: "",
   ingredient_2: "",
   unit: "Syrup",
   ptr: 27.04,
   gst_percent: "12%",
   gst_amount: 3.24,
   total_w_gst: 30.28,
   mrp: 60.9,
   pharma: "LAB",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 20,
   last_ordered_date: "29/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 62,
   brand_name: "Freelex",
   category: "Laxative",
   sub_category: "",
   ingredient_1: "Bisacodyl",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 4.39,
   gst_percent: "12%",
   gst_amount: 0.53,
   total_w_gst: 4.92,
   mrp: 12,
   pharma: "Leeford",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 30,
   last_ordered_date: "29/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 63,
   brand_name: "Chyreal forte",
   category: "Supplement",
   sub_category: "",
   ingredient_1: "Trypsin",
   ingredient_2: "Chymotrypsin",
   unit: "Tablet",
   ptr: 50.04,
   gst_percent: "12%",
   gst_amount: 6,
   total_w_gst: 56.04,
   mrp: 325,
   pharma: "Maxx",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "29/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 64,
   brand_name: "Urin Bag Polymed",
   category: "Equipment",
   sub_category: "",
   ingredient_1: "",
   ingredient_2: "",
   unit: "Equipment",
   ptr: 26.4,
   gst_percent: "5%",
   gst_amount: 1.32,
   total_w_gst: 27.72,
   mrp: 223,
   pharma: "Poly",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "29/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 65,
   brand_name: "Aliclair 500",
   category: "Antibiotic",
   sub_category: "",
   ingredient_1: "Clarithromycin",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 69,
   gst_percent: "12%",
   gst_amount: 8.28,
   total_w_gst: 77.28,
   mrp: 216.3,
   pharma: "Leeford",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 66,
   brand_name: "Piprataz inj",
   category: "Antibiotic",
   sub_category: "",
   ingredient_1: "Piperacillin",
   ingredient_2: "Tazobactum",
   unit: "Injection",
   ptr: 99,
   gst_percent: "12%",
   gst_amount: 11.88,
   total_w_gst: 110.88,
   mrp: 490.1,
   pharma: "Abbott",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 19,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 67,
   brand_name: "Alcid MPS",
   category: "Antacid",
   sub_category: "Antiflatulent",
   ingredient_1: "Aluminium",
   ingredient_2: "Magnesium, simethicone",
   unit: "Syrup",
   ptr: 21.86,
   gst_percent: "12%",
   gst_amount: 2.62,
   total_w_gst: 24.48,
   mrp: 99,
   pharma: "ALE",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 5,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 68,
   brand_name: "NS 100 ml",
   category: "Fluid",
   sub_category: "",
   ingredient_1: "Normal saline 0.9%",
   ingredient_2: "",
   unit: "Bottle",
   ptr: 11.5,
   gst_percent: "12%",
   gst_amount: 1.38,
   total_w_gst: 12.88,
   mrp: 17.71,
   pharma: "Alkem",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 20,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 69,
   brand_name: "Eterna 2 ml",
   category: "Antiemetic",
   sub_category: "",
   ingredient_1: "Ondansetron",
   ingredient_2: "",
   unit: "Injection",
   ptr: 9.5,
   gst_percent: "12%",
   gst_amount: 1.14,
   total_w_gst: 10.64,
   mrp: 12.75,
   pharma: "Blue Cross",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 50,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 70,
   brand_name: "Pantosec D SR",
   category: "Antacid",
   sub_category: "",
   ingredient_1: "Pantoprazole",
   ingredient_2: "Domperidone",
   unit: "Capsule",
   ptr: 33.4,
   gst_percent: "12%",
   gst_amount: 4.01,
   total_w_gst: 37.41,
   mrp: 114,
   pharma: "CIPLA",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 3,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 71,
   brand_name: "Tetanus toxoid",
   category: "Vaccine",
   sub_category: "",
   ingredient_1: "TT",
   ingredient_2: "",
   unit: "Injection",
   ptr: 9.2,
   gst_percent: "5%",
   gst_amount: 0.46,
   total_w_gst: 9.66,
   mrp: 11.4,
   pharma: "DAN",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 50,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 72,
   brand_name: "Eldervit Syp 200",
   category: "Supplement",
   sub_category: "",
   ingredient_1: "",
   ingredient_2: "",
   unit: "",
   ptr: 20,
   gst_percent: "18%",
   gst_amount: 3.6,
   total_w_gst: 23.6,
   mrp: null,
   pharma: "ELDER",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 5,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 73,
   brand_name: "Eldervit Syp 100",
   category: "Supplement",
   sub_category: "",
   ingredient_1: "",
   ingredient_2: "",
   unit: "",
   ptr: 11.5,
   gst_percent: "18%",
   gst_amount: 2.07,
   total_w_gst: 13.57,
   mrp: null,
   pharma: "ELDER",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 5,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 74,
   brand_name: "Broncofil-N",
   category: "Mucolytic",
   sub_category: "Bronchodilator",
   ingredient_1: "Acebrophylline",
   ingredient_2: "Acetylcysteine",
   unit: "Tablet",
   ptr: 82.2,
   gst_percent: "12%",
   gst_amount: 9.86,
   total_w_gst: 92.06,
   mrp: 200,
   pharma: "Leeford",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 75,
   brand_name: "Lee biotic Cap",
   category: "",
   sub_category: "",
   ingredient_1: "",
   ingredient_2: "",
   unit: "Capsule",
   ptr: 29.4,
   gst_percent: "18%",
   gst_amount: 5.29,
   total_w_gst: 34.69,
   mrp: 104,
   pharma: "Leeford",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 76,
   brand_name: "Benogermina Respule",
   category: "Probiotic",
   sub_category: "",
   ingredient_1: "Bacillus Clausii",
   ingredient_2: "",
   unit: "Respule",
   ptr: 12.94,
   gst_percent: "12%",
   gst_amount: 1.55,
   total_w_gst: 14.49,
   mrp: 55,
   pharma: "OT/Nectar",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 30,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 77,
   brand_name: "Leevron",
   category: "",
   sub_category: "",
   ingredient_1: "",
   ingredient_2: "",
   unit: "Gel",
   ptr: 13,
   gst_percent: "12%",
   gst_amount: 1.56,
   total_w_gst: 14.56,
   mrp: null,
   pharma: "OT/Nectar",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 6,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 78,
   brand_name: "Lycopen Red",
   category: "Supplement",
   sub_category: "",
   ingredient_1: "Lycopene",
   ingredient_2: "",
   unit: "Syrup",
   ptr: 22,
   gst_percent: "12%",
   gst_amount: 2.64,
   total_w_gst: 24.64,
   mrp: null,
   pharma: "OT/Nectar",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 5,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 79,
   brand_name: "Budefex 2 ml",
   category: "Bronchodilator",
   sub_category: "",
   ingredient_1: "Budesol",
   ingredient_2: "",
   unit: "respule",
   ptr: 265.65,
   gst_percent: "12%",
   gst_amount: 31.88,
   total_w_gst: 297.53,
   mrp: 788,
   pharma: "RANBAXY",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 1,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 80,
   brand_name: "Histac MPS Mint",
   category: "Antacid",
   sub_category: "Antiflatulent",
   ingredient_1: "Aluminium",
   ingredient_2: "Magnesium, simethicone",
   unit: "Syrup",
   ptr: 27.6,
   gst_percent: "12%",
   gst_amount: 3.31,
   total_w_gst: 30.91,
   mrp: 114,
   pharma: "RANBAXY",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 3,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 81,
   brand_name: "Ecoryl LS",
   category: "Cough syrup",
   sub_category: "Bronchodilator, mucolytic",
   ingredient_1: "Levosalbutamol",
   ingredient_2: "Ambroxol, guaiphenesin, menthol",
   unit: "Syrup",
   ptr: 24.84,
   gst_percent: "12%",
   gst_amount: 2.98,
   total_w_gst: 27.82,
   mrp: 99,
   pharma: "TARUN",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 10,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 82,
   brand_name: "Panzof IV",
   category: "Antacid",
   sub_category: "PPI",
   ingredient_1: "Pantoprazole",
   ingredient_2: "",
   unit: "Injection",
   ptr: 10,
   gst_percent: "12%",
   gst_amount: 1.2,
   total_w_gst: 11.2,
   mrp: 49.7,
   pharma: "TARUN",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 20,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 83,
   brand_name: "Tazilin",
   category: "Antibiotic",
   sub_category: "",
   ingredient_1: "Piperacillin",
   ingredient_2: "Tazobactum",
   unit: "Injection",
   ptr: 97.75,
   gst_percent: "12%",
   gst_amount: 11.73,
   total_w_gst: 109.48,
   mrp: 380,
   pharma: "Zydus",
   stockist: "Prasad Medical Agency",
   scm: "0",
   last_ordered_quantity: 30,
   last_ordered_date: "20/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 84,
   brand_name: "Alivia 4G",
   category: "Supplement",
   sub_category: "",
   ingredient_1: "Omega 3",
   ingredient_2: "Gingko biloba, ginseng, green tea",
   unit: "Tablet",
   ptr: 134.24,
   gst_percent: "18%",
   gst_amount: 24.16,
   total_w_gst: 158.4,
   mrp: 198,
   pharma: "Zed/Redvia",
   stockist: "VS Pharma",
   scm: "30+6",
   last_ordered_quantity: 30,
   last_ordered_date: "21/09/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 85,
   brand_name: "Uticam",
   category: "Supplement",
   sub_category: "UTI supplement",
   ingredient_1: "Cranberry",
   ingredient_2: "D Mannose, Potassium magnesium citrate",
   unit: "Powder",
   ptr: 32.85,
   gst_percent: "18%",
   gst_amount: 5.91,
   total_w_gst: 38.76,
   mrp: 40,
   pharma: "Trumac",
   stockist: "Well Care",
   scm: "50+10",
   last_ordered_quantity: 50,
   last_ordered_date: "08/09/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 86,
   brand_name: "Larzon",
   category: "Supplement",
   sub_category: "Gynec",
   ingredient_1: "L-Arginine",
   ingredient_2: "Proanthocyanin",
   unit: "Powder",
   ptr: 34.74,
   gst_percent: "18%",
   gst_amount: 6.25,
   total_w_gst: 40.99,
   mrp: 50,
   pharma: "Crinova",
   stockist: "Well Care",
   scm: "40+8",
   last_ordered_quantity: 40,
   last_ordered_date: "19/07/22",
   field18: "25+5",
   field19: "06/08/22",
   field20: "",
   field21: ""
 },
 {
   sr_no: 87,
   brand_name: "Myorin tab",
   category: "Supplement",
   sub_category: "Gynec",
   ingredient_1: "Myo inositol",
   ingredient_2: "D chiro inositol, chromium, vit D3",
   unit: "Tablet",
   ptr: 125.08,
   gst_percent: "18%",
   gst_amount: 22.51,
   total_w_gst: 147.59,
   mrp: 180,
   pharma: "Crinova",
   stockist: "Well Care",
   scm: "30+6",
   last_ordered_quantity: 30,
   last_ordered_date: "19/07/22",
   field18: "20+4",
   field19: "05/09/22",
   field20: "15+3",
   field21: "06/08/22"
 },
 {
   sr_no: 88,
   brand_name: "Arzistal",
   category: "Supplement",
   sub_category: "Gynec",
   ingredient_1: "L-Arginine",
   ingredient_2: "Zinc sulphate, folic acid",
   unit: "Powder",
   ptr: null,
   gst_percent: "",
   gst_amount: 0,
   total_w_gst: 0,
   mrp: 65,
   pharma: "Leeford",
   stockist: "",
   scm: "",
   last_ordered_quantity: null,
   last_ordered_date: "",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 89,
   brand_name: "Zilargyn-Z5",
   category: "Supplement",
   sub_category: "Gynec",
   ingredient_1: "L-Arginine",
   ingredient_2: "",
   unit: "Powder",
   ptr: null,
   gst_percent: "",
   gst_amount: 0,
   total_w_gst: 0,
   mrp: 49,
   pharma: "Bharat Serum",
   stockist: "",
   scm: "",
   last_ordered_quantity: null,
   last_ordered_date: "",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 90,
   brand_name: "Dinolex-2",
   category: "Supplement",
   sub_category: "Gynec",
   ingredient_1: "Dienogest",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 435.62,
   gst_percent: "12%",
   gst_amount: 52.27,
   total_w_gst: 487.89,
   mrp: 595,
   pharma: "Trumac",
   stockist: "Well Care",
   scm: "15+3",
   last_ordered_quantity: null,
   last_ordered_date: "05/09/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 91,
   brand_name: "Cysvia 35",
   category: "Hormones",
   sub_category: "Gynec",
   ingredient_1: "Ethinylestradiol",
   ingredient_2: "Cyproterone",
   unit: "Tablet",
   ptr: 226.96,
   gst_percent: "12%",
   gst_amount: 27.24,
   total_w_gst: 254.2,
   mrp: 310,
   pharma: "Osiante",
   stockist: "Well Care",
   scm: "25+5",
   last_ordered_quantity: null,
   last_ordered_date: "13/09/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 92,
   brand_name: "Drosmyra",
   category: "Hormones",
   sub_category: "Gynec",
   ingredient_1: "Drosperinone",
   ingredient_2: "Ethinylestradiol",
   unit: "Tablet",
   ptr: 399,
   gst_percent: "12%",
   gst_amount: 47.88,
   total_w_gst: 446.88,
   mrp: 545,
   pharma: "Osiante",
   stockist: "Well Care",
   scm: "25+5",
   last_ordered_quantity: null,
   last_ordered_date: "13/09/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 93,
   brand_name: "Larzon",
   category: "Supplement",
   sub_category: "Gynec",
   ingredient_1: "L-Arginine",
   ingredient_2: "Proanthocyanin",
   unit: "Powder",
   ptr: 41.69,
   gst_percent: "18%",
   gst_amount: 7.5,
   total_w_gst: 49.19,
   mrp: 60,
   pharma: "Crinova",
   stockist: "Well Care",
   scm: "50+10",
   last_ordered_quantity: 50,
   last_ordered_date: "21/09/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 94,
   brand_name: "Paning DSR",
   category: "Antacid",
   sub_category: "",
   ingredient_1: "Pantoprazole",
   ingredient_2: "Domperidone",
   unit: "Capsule",
   ptr: 60.82,
   gst_percent: "12%",
   gst_amount: 7.3,
   total_w_gst: 68.12,
   mrp: 85,
   pharma: "Celife",
   stockist: "Jay Balaji",
   scm: "200+40",
   last_ordered_quantity: 200,
   last_ordered_date: "28/07/22",
   field18: "200+40",
   field19: "19/09/22",
   field20: "",
   field21: ""
 },
 {
   sr_no: 95,
   brand_name: "Paning 40",
   category: "Antacid",
   sub_category: "",
   ingredient_1: "Pantoprazole",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 42.93,
   gst_percent: "12%",
   gst_amount: 5.15,
   total_w_gst: 48.08,
   mrp: 60,
   pharma: "Celife",
   stockist: "Jay Balaji",
   scm: "200+40",
   last_ordered_quantity: 200,
   last_ordered_date: "28/07/22",
   field18: "50+10",
   field19: "19/09/22",
   field20: "",
   field21: ""
 },
 {
   sr_no: 96,
   brand_name: "ODHIST M",
   category: "Antihistamine",
   sub_category: "",
   ingredient_1: "Levocetirizine",
   ingredient_2: "Montelukast",
   unit: "Tablet",
   ptr: 57.84,
   gst_percent: "12%",
   gst_amount: 6.94,
   total_w_gst: 64.78,
   mrp: 80,
   pharma: "Celife",
   stockist: "Jay Balaji",
   scm: "100+20",
   last_ordered_quantity: 100,
   last_ordered_date: "28/07/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 97,
   brand_name: "Defgate-6",
   category: "Corticosteroid",
   sub_category: "",
   ingredient_1: "Deflazacort",
   ingredient_2: "",
   unit: "Tablet",
   ptr: 54.64,
   gst_percent: "12%",
   gst_amount: 6.56,
   total_w_gst: 61.2,
   mrp: 85,
   pharma: "Celife",
   stockist: "Jay Balaji",
   scm: "100+20",
   last_ordered_quantity: 100,
   last_ordered_date: "28/07/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 98,
   brand_name: "Zo D drops",
   category: "",
   sub_category: "",
   ingredient_1: "",
   ingredient_2: "",
   unit: "Syrup",
   ptr: 19.86,
   gst_percent: "12%",
   gst_amount: 2.38,
   total_w_gst: 22.24,
   mrp: 27.8,
   pharma: "FDC",
   stockist: "Jay Balaji",
   scm: "0",
   last_ordered_quantity: 5,
   last_ordered_date: "12/08/22",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 },
 {
   sr_no: 99,
   brand_name: "Duvadilan",
   category: "",
   sub_category: "",
   ingredient_1: "",
   ingredient_2: "",
   unit: "",
   ptr: null,
   gst_percent: "",
   gst_amount: 0,
   total_w_gst: 0,
   mrp: null,
   pharma: "",
   stockist: "",
   scm: "",
   last_ordered_quantity: null,
   last_ordered_date: "",
   field18: "",
   field19: "",
   field20: "",
   field21: ""
 }
]
